### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by klauer** [klauer/ioc-useless-test#3]
- [x] Have some records match gateway settings
- [x] Fix happi settings
- [x] Install gdb so its introspection will work
- [ ] Add a command that shows that gdb introspection is working
- [ ] Check for other functionality not exhibited here
- [ ] Move CI jobs to pcds-ci-helpers
- [ ] Build the IOC binary with pib
- [ ] Make whatrecord hide PV Map if there's only one IOC?
- [ ] Make whatrecord hide host column if there's no info for any IOC (IOC listing)?
